nodeLinker: pnp

packageExtensions:
  "storybook@*":
    dependencies:
      "@storybook/react-vite": "*"
      "vite": "^5"
      "react": "^18"
      "react-dom": "^18"

  "@storybook/react-vite@*":
    dependencies:
      "@storybook/addon-docs": "*"
